plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

neoForge {
    version = '21.1.219'
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':anno-core')
    api project(':anno-mod-common')
}

java {
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'KessokuMaven'
            url = version.toString().endsWith('-SNAPSHOT')
                    ? 'https://maven.kessokuteatime.work/snapshots'
                    : 'https://maven.kessokuteatime.work/releases'
            credentials {
                username = System.getenv('K_MAVEN_USERNAME')
                password = System.getenv('K_MAVEN_TOKEN')
            }
        }
    }
}
